"""integration v1 accounts inbox and product data

Revision ID: 651eb026c9bd
Revises: 8f80bf2b83ca
"""

import sqlalchemy as sa
from alembic import op

revision = "651eb026c9bd"
down_revision = "8f80bf2b83ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column("update_id", sa.BigInteger(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=32), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bot_id", "update_id"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name"),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_categories_user_id"), ["user_id"], unique=False)

    op.create_table(
        "link_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("bot_id", sa.BigInteger(), nullable=True),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("expires_at", sa.Float(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code_hash"),
    )
    with op.batch_alter_table("link_requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_link_requests_user_id"), ["user_id"], unique=False)

    op.create_table(
        "product_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("operation_id", sa.String(length=100), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("is_test", sa.Boolean(), nullable=False),
        sa.Column("app_version", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("occurred_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", "operation_id"),
    )
    with op.batch_alter_table("product_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_product_events_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_events_occurred_at"), ["occurred_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_events_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "provider_usage",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.String(length=100), nullable=False),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("tariff_version", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_tokens", sa.Integer(), nullable=True),
        sa.Column("stt_seconds", sa.Float(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("occurred_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    with op.batch_alter_table("provider_usage", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_provider_usage_occurred_at"), ["occurred_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_provider_usage_operation_id"), ["operation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_provider_usage_user_id"), ["user_id"], unique=False)

    op.create_table(
        "telegram_identities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("delivery_status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bot_id", "telegram_user_id"),
        sa.UniqueConstraint("bot_id", "user_id"),
    )
    with op.batch_alter_table("telegram_identities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_telegram_identities_user_id"), ["user_id"], unique=False)

    op.create_table(
        "items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("note_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.Float(), nullable=True),
        sa.Column("category_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint("kind IN ('note', 'idea', 'task', 'goal', 'plan')", name="ck_items_kind"),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["notes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_items_note_id"), ["note_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_items_user_id"), ["user_id"], unique=False)

    op.create_table(
        "reminders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("note_id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=True),
        sa.Column("scheduled_at", sa.Float(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("confirmed_at", sa.Float(), nullable=False),
        sa.CheckConstraint("generation >= 1", name="ck_reminders_generation"),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["note_id"],
            ["notes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reminders_scheduled_at"), ["scheduled_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_reminders_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_reminders_user_id"), ["user_id"], unique=False)

    op.create_table(
        "outbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("reminder_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("bot_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("lease_token_hash", sa.String(length=64), nullable=True),
        sa.Column("lease_until", sa.Float(), nullable=True),
        sa.Column("authorized_at", sa.Float(), nullable=True),
        sa.Column("callback_token_hash", sa.String(length=64), nullable=True),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("retry_at", sa.Float(), nullable=True),
        sa.Column("result_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reminder_id"],
            ["reminders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("callback_token_hash"),
        sa.UniqueConstraint("reminder_id", "generation"),
    )
    with op.batch_alter_table("outbox", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_outbox_reminder_id"), ["reminder_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_outbox_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_outbox_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("captures", schema=None) as batch_op:
        batch_op.add_column(sa.Column("channel", sa.String(length=16), server_default="web", nullable=False))
        batch_op.add_column(
            sa.Column("processing_mode", sa.String(length=16), server_default="ai", nullable=False)
        )

    op.add_column("captures", sa.Column("input_kind", sa.String(16), server_default="text", nullable=False))
    op.add_column("captures", sa.Column("audio_key", sa.String(100), nullable=True))
    op.add_column("captures", sa.Column("audio_seconds", sa.Float(), nullable=True))
    op.add_column("captures", sa.Column("audio_bytes", sa.Integer(), nullable=True))
    op.add_column("captures", sa.Column("transcript", sa.Text(), nullable=True))
    op.add_column(
        "captures", sa.Column("transcript_version", sa.Integer(), server_default="1", nullable=False)
    )
    op.add_column("notes", sa.Column("structure_confirmed_at", sa.Float(), nullable=True))
    if op.get_bind().dialect.name == "sqlite":
        op.execute("ALTER TABLE notes ADD COLUMN category_id VARCHAR(36) REFERENCES categories(id)")
    else:
        op.add_column("notes", sa.Column("category_id", sa.String(36), nullable=True))
        op.create_foreign_key("fk_notes_category", "notes", "categories", ["category_id"], ["id"])

    # Add columns without rebuilding users: an existing SQLite database has FKs
    # from sessions/captures/notes and rebuilding the parent would lose integrity.
    dialect = op.get_bind().dialect.name
    if dialect == "sqlite":
        op.execute(
            "ALTER TABLE users ADD COLUMN role VARCHAR(16) NOT NULL DEFAULT 'user' "
            "CONSTRAINT ck_users_role CHECK (role IN ('user', 'admin'))"
        )
    else:
        op.add_column("users", sa.Column("role", sa.String(16), server_default="user", nullable=False))
        op.create_check_constraint("ck_users_role", "users", "role IN ('user', 'admin')")
    op.add_column("users", sa.Column("is_test", sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column("users", sa.Column("source", sa.String(100), server_default="unknown", nullable=False))
    op.add_column("users", sa.Column("created_at", sa.Float(), nullable=True))
    op.add_column("users", sa.Column("first_login_at", sa.Float(), nullable=True))
    # Historic signup times are unknown, not the time this migration was applied.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name != "sqlite":
        op.drop_constraint("ck_users_role", "users", type_="check")
    for column in ("first_login_at", "created_at", "source", "is_test", "role"):
        op.drop_column("users", column)

    if op.get_bind().dialect.name != "sqlite":
        op.drop_constraint("fk_notes_category", "notes", type_="foreignkey")
    op.drop_column("notes", "category_id")
    op.drop_column("notes", "structure_confirmed_at")
    for column in (
        "transcript_version",
        "transcript",
        "audio_bytes",
        "audio_seconds",
        "audio_key",
        "input_kind",
    ):
        op.drop_column("captures", column)
    op.drop_column("captures", "processing_mode")
    op.drop_column("captures", "channel")

    with op.batch_alter_table("outbox", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outbox_user_id"))
        batch_op.drop_index(batch_op.f("ix_outbox_status"))
        batch_op.drop_index(batch_op.f("ix_outbox_reminder_id"))

    op.drop_table("outbox")
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reminders_user_id"))
        batch_op.drop_index(batch_op.f("ix_reminders_status"))
        batch_op.drop_index(batch_op.f("ix_reminders_scheduled_at"))

    op.drop_table("reminders")
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_items_user_id"))
        batch_op.drop_index(batch_op.f("ix_items_note_id"))

    op.drop_table("items")
    with op.batch_alter_table("telegram_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_telegram_identities_user_id"))

    op.drop_table("telegram_identities")
    with op.batch_alter_table("provider_usage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_usage_user_id"))
        batch_op.drop_index(batch_op.f("ix_provider_usage_operation_id"))
        batch_op.drop_index(batch_op.f("ix_provider_usage_occurred_at"))

    op.drop_table("provider_usage")
    with op.batch_alter_table("product_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_product_events_session_id"))
        batch_op.drop_index(batch_op.f("ix_product_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_product_events_name"))

    op.drop_table("product_events")
    with op.batch_alter_table("link_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_link_requests_user_id"))

    op.drop_table("link_requests")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_user_id"))

    op.drop_table("categories")
    op.drop_table("inbox")
    # ### end Alembic commands ###
